version: '3.3'
services:
  client:
    build:
      context: ./client
  api:
    build:
      context: ./server
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'